### ISSUE TITLE
Lua error: attempt to index a nil value 

### ISSUE THREAD

**Issue by andrewpbray** [coatless/quarto-webr#107]
Hello!

I'm encountering a Lua error on rendering a minimal document with `webr` into an existing website. The error message:

```
Error running filter /opt/quarto/share/filters/main.lua:
/home/rstudio/stat20/_extensions/coatless/webr/webr.lua:364: attempt to index a nil value (local 'contents')
stack traceback:
	/home/rstudio/stat20/_extensions/coatless/webr/webr.lua:312: in global 'initializationWebR'
	/home/rstudio/stat20/_extensions/coatless/webr/webr.lua:328: in global 'ensureWebRSetup'
	/home/rstudio/stat20/_extensions/coatless/webr/webr.lua:437: in function </home/rstudio/stat20/_extensions/coatless/webr/webr.lua:408>
	[C]: in ?
	[C]: in method 'walk'
	/opt/quarto/share/filters/main.lua:171: in function 'run_emulated_filter'
	/opt/quarto/share/filters/main.lua:[449](https://github.com/stat20/stat20/actions/runs/6906101994/job/18795063686#step:4:450): in local 'callback'
	[string "..."]:1789: in field 'withScriptFile'
	/opt/quarto/share/filters/main.lua:452: in upvalue 'run_emulated_filter_chain'
	/opt/quarto/share/filters/main.lua:495: in function </opt/quarto/share/filters/main.lua:476>
stack traceback:
	/opt/quarto/share/filters/main.lua:171: in function 'run_emulated_filter'
	/opt/quarto/share/filters/main.lua:449: in local 'callback'
	[string "..."]:1789: in field 'withScriptFile'
	/opt/quarto/share/filters/main.lua:[452](https://github.com/stat20/stat20/actions/runs/6906101994/job/18795063686#step:4:453): in upvalue 'run_emulated_filter_chain'
	/opt/quarto/share/filters/main.lua:495: in function </opt/quarto/share/filters/main.lua:476>
```

The document itself is quite simple:

````
---
title: "Exercises"
resources:
  - webr-serviceworker.js
  - webr-worker.js
filters:
  - webr
webr:
  show-startup-message: false 
---

Practice fitting a linear model!

```{webr-r}
fit = lm(mpg ~ am, data = mtcars)
summary(fit)
```
````
This document exists in a subdirectory of the website, with the extension installed at the root level and the .js files copied into the same subdirectory as the document.

Look at line 364 of the lua file, looks like you could add a check for `nil` in `substitute_in_file()`, though looking to where that function is called, it looks like you've put in some logic that should prevent it from passing `nil`s to the function. Hmmm...

The error message came up on CI on a public repo, which you can see here:

[https://github.com/stat20/stat20/actions/runs/6906101994/job/18795063686#step:4:443](https://github.com/stat20/stat20/actions/runs/6906101994/job/18795063686#step:4:443
)

Running `webr` version: 0.3.7 with quarto version 1.3.433.

**Comment by coatless** [comment]
@andrewpbray the full contents of the extension did not get added to the repo. 

https://github.com/stat20/stat20/tree/09f9f55ffb8dd1a81b7d9a7db9ea8f2fc1943952/_extensions/coatless/webr

Required file layout: 

https://github.com/coatless/quarto-webr/tree/main/_extensions/webr

Note the absence of `webr-*.html`

I think this is due to a global lock on `.html` files not being commitable. 

https://github.com/stat20/stat20/blob/09f9f55ffb8dd1a81b7d9a7db9ea8f2fc1943952/.gitignore#L18

**Comment by andrewpbray** [comment]
Ah! Good catch! Wow, that would have taken me awhile to find. I'll have to set that .gitignore more finely. I hadn't thought about .html files that come through extensions, but they're actually not uncommon. Thanks!

**Comment by coatless** [comment]
No worries, hope the test goes well 😃
