### ISSUE TITLE
[Bug]: Disable automatic rendering of links in webR code cell output

### ISSUE THREAD

**Issue by gvelasq** [coatless/quarto-webr#115]
### Bug description

Thank you for this excellent extension. @ivelasq and I are planning to use it for her Quarto [blog](https://ivelasq.rbind.io). When running the following code in a webR code cell in a Quarto HTML document, the output is automatically rendered into a live hyperlink, which is unexpected behavior. The desired behavior is for the HTML code (not the live hyperlink) to be displayed as output, as it is in the 1) R console in RStudio, 2) in the [webR REPL demo](https://webr.r-wasm.org/latest), 3) the webR website's [interactive console](https://docs.r-wasm.org/webr/latest/#interactive-r-code-editor), or in 4/5) .qmd/.Rmd files that are rendered/knit in RStudio.

```{r}
# This function converts a markdown link into HTML
"[Posit](https://posit.co)" |> (\(.) {
  text <- sub("\\].*", "", sub(".*\\[", "", .))
  url <- sub("\\).*", "", sub(".*\\(", "", .))
  
  writeLines(noquote(paste0('<a href="', url, '" target = "_blank">', text, '</a>')))
})()
```

### Steps to reproduce

1. **(Unexpected)** To reproduce, copy/paste the code above into a webR code block in this [draft blog post](https://ivelasq.rbind.io/blog/not-so-basic-base-r-functions/#noquote), and click 'Run Code'. The code for the blog post can be found [here](https://github.com/ivelasq/pipedream/blob/main/blog/not-so-basic-base-r-functions/index.qmd#L142).

Rather than the output of the code cell being a line of HTML code created by `writeLines(noquote(paste0(...)))`, the output is instead a clickable hyperlink to the Posit website. Ideally, there could be a option (at the code chunk level, not at the YAML header level) to disable/enable this behavior. We tried `#| output: asis` but that did not work.

<img width="819" alt="Screenshot 2023-12-04 at 11 28 29 PM" src="https://github.com/coatless/quarto-webr/assets/20712598/e5c2979e-2a30-4f9e-a399-aa6eaec0b480">

Below for reference are examples that do display the expected behavior:

2. **(Expected)** Copy/paste the code above into the [webR REPL demo](https://webr.r-wasm.org/latest):
<img width="713" alt="Screenshot 2023-12-05 at 11 54 58 PM" src="https://github.com/coatless/quarto-webr/assets/20712598/7fc93f88-0de0-48cd-8e7d-2d0abd93f0cb">

3. **(Expected)** Copy/paste the code above into the webR website's [interactive console](https://docs.r-wasm.org/webr/latest/#interactive-r-code-editor):
<img width="776" alt="Screenshot 2023-12-04 at 11 26 43 PM" src="https://github.com/coatless/quarto-webr/assets/20712598/43deb29e-4ccb-4114-ac75-5b328fcc2b4c">

4. **(Expected)** Copy/paste the code above into a blank .qmd and render the document:
<img width="810" alt="Screenshot 2023-12-04 at 11 22 50 PM" src="https://github.com/coatless/quarto-webr/assets/20712598/a05766a3-d75c-484a-843b-32c8e2aa8678">

5. **(Expected)** Copy/paste the code above into a blank .Rmd and knit the document:
<img width="923" alt="Screenshot 2023-12-04 at 11 22 17 PM" src="https://github.com/coatless/quarto-webr/assets/20712598/2ad79abb-9040-456c-bc53-4ec541feaf06">

### Your environment

- IDE: RStudio 2023.09.1
- OS: macOS Ventura 13.6

### Quarto check output

```bash
Usage:   quarto 
  Version: 1.4.504
```

**Comment by coatless** [comment]
Thanks for the detailed issue! 

We're using `innerHTML` instead of `innerText` to update the document for output to provide annotation to differentiate between `STDOUT` and `STDERR` (black/red text). Specifically, we're doing it at: 

https://github.com/coatless/quarto-webr/blob/f81f1b51a3c620841602eb0bc429f8f45df3d84a/_extensions/webr/webr-context-interactive.html#L234-L237

This likely requires a modification in the mapping code to return output as an untouched HTML element.

https://github.com/coatless/quarto-webr/blob/f81f1b51a3c620841602eb0bc429f8f45df3d84a/_extensions/webr/webr-context-interactive.html#L187-L193

---

### Aside

We do not have any of the built-in Quarto code cell options yet. That's why you're seeing the `output: 'asis'` not change anything.

**Comment by ivelasq** [comment]
Thank you so much, @coatless ! 🎉

**Comment by gvelasq** [comment]
@coatless we really appreciate your prompt reply and fix!

**Comment by coatless** [comment]
Just an FYI @gvelasq & @ivelasq, in #141 some features of `results` (not `output`) are now available. 

**>>> There would be _no_ changes required if you update to the PR/future version. <<<**

For those who stumble upon this issue ticket, if you wanted to allow for the original behavior of having the text become a hyperlink, then this is now possible by specifying inside the code cell: `results: 'asis'`
