### ISSUE TITLE
Shim install.packages()

### ISSUE THREAD

**Issue by coatless** [coatless/quarto-webr#122]
With webR v0.2.2, there is now a shim for `install.packages()`. 

https://docs.r-wasm.org/webr/latest/api/r.html#shim_install

This requires calling the installation during the setup routine.

```js
webr.evalRVoid("webr::shim_install()")
```

So, we'd avoid getting an error like:

```r
> install.packages("jsonlite")
Error in install.packages("jsonlite"): 
  This version of R is not setup to install source packages
If it was installed from an RPM, you may need the R-devel RPM
```

**Comment by coatless** [comment]
@jimjam-slam  Psst, `install.packages()` should also now redirect over to `webr::install()` :) 

https://jamesgoldie.dev/writing/your-new-r-package-webr/#fnref1

**Comment by jimjam-slam** [comment]
Oh, awesome! I'll update the post when I can!
