### ISSUE TITLE
Installing the webr extension

### ISSUE THREAD

**Issue by neuwirthe** [coatless/quarto-webr#123]
In the instructions you say one has to run the command

`quarto add coatless/quarto-webr`

to install the web extension.
That does not work in my configuration.
Running

`quarto install extension coatless/quarto-webr`
 
solved the problem.

Perhaps you want to update your README page

**Comment by coatless** [comment]
Hi @neuwirthe, 

Thanks for the note. I would mention that this likely means the copy of Quarto being used is out-of-date. This may be problematic soon as we're aiming to update the minimum version of Quarto required for the extension. I would suggest either updating [RStudio (2023.12.0+369 or later)](https://posit.co/download/rstudio-desktop/) and/or the standalone [Quarto (>= 1.3.*)](https://quarto.org/docs/download/) versions.

**Comment by neuwirthe** [comment]
Thanks,
I am on a Mac, and I do updates regularly.
For tools, I huse homebrew. 
Somehow quarto was not update.
I had version 1.0.38.
Explicitly doing
brew install quarto 
gave me version 1.3.450
and now the installation works.

Thanks
Erich

**Comment by coatless** [comment]
@neuwirthe great to hear! 

One minor note is the version of [`quarto` installed by `brew` uses a `cask`](https://formulae.brew.sh/cask/quarto
) or the official Quarto installer in a headless mode. So, the installation should be with:

```sh
brew install --cask quarto
```

I'd similarly advise the same for [`R`](https://formulae.brew.sh/cask/r) and [`RStudio`](https://formulae.brew.sh/cask/rstudio), e.g. 

```sh
brew install --cask r rstudio
```

**Comment by coatless** [comment]
I'm going to go ahead and close out this issue as the problem was resolved.
