### ISSUE TITLE
How to use Actions?

### ISSUE THREAD

**Issue by PMassicotte** [coatless/quarto-webr#126]
### What's your question?

Hi, thank you for this excellent extension.

I am trying to use actions to build/deploy a revealjs presentation on gh-pages. Locally it works fine. The action also runs fine (i.e., no error), but when I load the webpage/presentation, the `webr-r` chunk are not displaying.

My workflow:

https://github.com/PMassicotte/test-webr/blob/main/.github/workflows/_publish.yml

The rendered page:

https://pmassicotte.github.io/test-webr/

Note that if I use `quarto publish gh-pages`, the presentation is published correctly.

**Comment by coatless** [comment]
@PMassicotte sent a PR upstream with a version pin to the latest Quarto RC candidate for 1.4. This is likely a stop-gap measure as the next version of Quarto should soon be released and, thus, the `latest` tag would be updated.

If you want to explore a bit more in Quarto works, definitely check out:

- This repository's [`publish-demo.yml`](https://github.com/coatless/quarto-webr/blob/main/.github/workflows/publish-demo.yml) workflow.
- My quarto template book repository (setups both R & Python)'s [`quarto-render.yml`](https://github.com/coatless-tutorials/quarto-book-template/blob/main/.github/workflows/quarto-render.yml) workflow.
