### ISSUE TITLE
[Bug]: OJS doesn't show output anymore

### ISSUE THREAD

**Issue by guillaumechaumet** [coatless/quarto-webr#136]
### Bug description

For 3 days, OJS chunk doesn't show output after a new quarto_render.
The browser console output show the following messages :
Uncaught TypeError: Node.appendChild: Argument 1 is not an object
Uncaught TypeError: window._ojs.runtime is undefined

Others chunks types are fully functionnal 

### Steps to reproduce

````md
---
title: "Example"
format: 
  html:
    self-contained: true
engine: knitr
webr: 
filters:
 - webr
---

```{r}
lettres = LETTERS
Num = 1:5

ojs_define(lettres)
ojs_define(Num)
```


```{ojs input}
viewof x = Inputs.select(
  lettres, 
  {label: "letters"}
)

viewof y = Inputs.select(
  Num,
  {label: "numbers"}
)
```
````

### Your environment

IDE: Neovim OS: Mac Osx Ventura and Debian Bookworm

### Quarto check output

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.450
      Path: /Users/xxxxxxxx/Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.7
      Path: /usr/local/opt/python@3.11/bin/python3.11
      Jupyter: 5.2.0
      Kernels: python3

(/) Checking Jupyter engine render....0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[✓] Checking Jupyter engine render....OK

(\) Checking R installation...........Beware: RProfile not empty
[✓] Checking R installation...........OK
      Version: 4.1.2
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Users/xxxxxxx/Library/R/x86_64/4.1/library
        - /System/Volumes/Data/Network/LibraryAB/Frameworks/R.framework_4.1.2/Versions/4.1/Resources/library
      knitr: 1.41
      rmarkdown: 2.18

[✓] Checking Knitr engine render......OK

## Edit

Minor formatting edits to MWE.

**Comment by coatless** [comment]
I think you want the main Quarto repository as they are the ones that support the `ojs_define()` in an `{r}` cell. 

We're focused on supporting `{webr-r}` cells.


P.S. If that's not the case, a couple of quick notes:

1. The `{quarto-webr}` extension does not support `self-contained`. Moreover, the `webr` key is empty. So, you probably want: 

```yaml
---
title: "Example"
format: html
engine: knitr
filters:
 - webr
---
```

2. There is no `webr-r` code cell active. The `{r}` cell would need to go to `{webr-r}`.

````
```{webr-r}

lettres = LETTERS

Num = 1:5

ojs_define(lettres)

ojs_define(Num)

```
````

**Comment by guillaumechaumet** [comment]
Thank you for your fast response. Thank to you, I think there is the solution here :
https://github.com/quarto-dev/quarto-cli/issues/8372
