### ISSUE TITLE
[Bug]: webr and pseudocode extensions will conflict

### ISSUE THREAD

**Issue by ChoCho66** [coatless/quarto-webr#140]
### Bug description

webr and [pseudocode](https://github.com/leovan/quarto-pseudocode) extensions will conflict.

There is no problem in quarto-webr@0.0.4 (format: revealjs)

<img width="981" alt="截圖 2024-01-30 14 55 36" src="https://github.com/coatless/quarto-webr/assets/72805700/3520cc25-3c67-4ef4-bdc0-09d3eb53e0a1">

But under the latest version of webr (version: 0.4.0-dev.7), it will be as shown below (there is also a problem in format html)

<img width="1029" alt="截圖 2024-01-30 14 56 56" src="https://github.com/coatless/quarto-webr/assets/72805700/861acde9-6385-4bc6-b549-2f95ba9c44bc">

The version of pseudocode is 1.0.0.

### Steps to reproduce

This is a minimal template.
````qmd
---
title: "Quarto Extension pseudocode and webr"
filters:
  - pseudocode
  - webr
format:
  # html:
  revealjs:
    fontsize: 20pt
    include-in-header:
      text: |
        <script>
        MathJax = {
          loader: {
            load: ['[tex]/boldsymbol']
          },
          tex: {
            tags: "all",
            inlineMath: [['$','$'], ['\\(','\\)']],
            displayMath: [['$$','$$'], ['\\[','\\]']],
            processEscapes: true,
            processEnvironments: true,
            packages: {
              '[+]': ['boldsymbol']
            }
          }
        };
        </script>
        <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>
---

## Test text-style

```{webr-r}
print(1)
```

Test text-style is shown as @alg-test-text-style.

```pseudocode
#| label: alg-test-text-style
#| html-indent-size: "1.2em"
#| html-comment-delimiter: "//"
#| html-line-number: true
#| html-line-number-punc: ":"
#| html-no-end: false
#| pdf-placement: "htb!"
#| pdf-line-number: true

\begin{algorithm}
\caption{Test text-style}
\begin{algorithmic}
\Require some preconditions
\Ensure some postconditions
\Procedure{Test-Commands}{}
  \State \textnormal{textnormal,} \textrm{textrm,} \textsf{textsf,} \texttt{texttt.}
  \State \textbf{textbf,} \textmd{textmd.}
  \State \textup{textup,} \textit{textit,} \textsc{textsc,} \textsl{textsl.}
  \State \uppercase{uppercase,} \lowercase{LOWERCASE.}
\EndProcedure
\Procedure{Test-Colors}{}
  \State \Comment{feature not implemented}
\EndProcedure
\end{algorithmic}
\end{algorithm}
```
````

### Your environment

- IDE: VSCode Version: 1.85.2 (Universal)
- macOS: Sonoma 14.2.1

### Quarto check output

```bash
Quarto 1.4.547
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.547
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/chocho/Library/TinyTeX/bin/universal-darwin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.6
      Path: /opt/homebrew/opt/python@3.11/bin/python3.11
      Jupyter: 5.5.0
      Kernels: julia-1.8

      NOTE: No Jupyter kernel for Python found

[✓] Checking R installation...........OK
      Version: 4.2.2
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library
      knitr: 1.45
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
```

**Comment by coatless** [comment]
I can verify this; but, I don't see an easy solution as this relies on how `psuedocode` is initialized.

Plus, we've come quite a ways from 0.0.4. So, I'm not sure there's much I do to make the extensions play nicely with each other.

**Comment by ChoCho66** [comment]
Thanks for the reply!

By the way, I just tested that under web-r 0.1.0, the pseudocode extension can still work (it’s just that revealjs cannot run webr).
As shown below
<img width="1107" alt="截圖 2024-01-30 16 24 31" src="https://github.com/coatless/quarto-webr/assets/72805700/eb3168b9-1943-4cd1-b96c-a46760efbb40">

When web-r went from 0.1.0 to 0.2.0, there was a problem that the pseudocode extension could not work.

**Comment by coatless** [comment]
@ChoCho66 so, this is related to the switch over to the Monaco Editor (we previously used code mirror). 

Relevant diff: https://github.com/coatless/quarto-webr/compare/0.1.0...0.2.0

For some reason `psuedocode` with monaco isn't starting up correctly leading to it not being registered. 

<img width="911" alt="Screenshot of the initialization error for `psuedocode`" src="https://github.com/coatless/quarto-webr/assets/833642/21fcc971-2136-4a20-abca-5acb4632a9c7">

Glancing at the [initialization code](https://github.com/leovan/quarto-pseudocode/blob/4fc707cd6e60a137b6ff88f9ff82f4d03df354d2/_extensions/pseudocode/after_body.html), I think they're using a problematic way to wait for the document DOM to be loaded.  The upstream maintainer of `psuedocode` likely needs something like: 

```js
document.addEventListener("DOMContentLoaded", function(event){
  // your code here
});
```

https://developer.mozilla.org/en-US/docs/Web/API/Document/DOMContentLoaded_event

Though, that's the first thing that comes to my mind. Our hands are tied with how we need to initialize Monaco.
