### ISSUE TITLE
parsermd 0.1.3 adds “unnamed-chunk-n”

### ISSUE THREAD

**Issue by davidkane9** [coatless/quarto-webr#144]
I think this is the explanation of the bug you just tweeted about

**Comment by coatless** [comment]
@davidkane9 it's a feature -- not a bug -- with respect to the `label` cell option that we just added! It was designed to pay homage to `knitr`, where unlabeled cells are given as `unnamed-chunk-1`. (Similar in scope to what `parsermd` is doing 😄 .)

**Comment by davidkane9** [comment]
Ahh. My mistake! Good luck with your continued progress. I am eager to switch my textbook over to web-r someday.

**Comment by coatless** [comment]
@davidkane9 thanks! Let me know if there is any key feature missing or you'd like help in porting. We're finalizing 4.0 and working on a roadmap for 4.1:

https://github.com/coatless/quarto-webr/milestone/6

You can see other features planned for 4.x here: 

https://github.com/coatless/quarto-webr/milestone/4
