### ISSUE TITLE
[Feature]: Support testing code and displaying feedback for interactive coding exercises

### ISSUE THREAD

**Issue by joelostblom** [coatless/quarto-webr#161]
### Feature Description

I am interested in creating coding exercises as part of a text book and I'm trying to explore if quarto-webr can be used for this purpose. The criteria I have in mind are the following:

- Inlined in the textbook as a single cell with a run button (this seems possible based on https://quarto-webr.thecoatlessprofessor.com/)
- Can run some type of tests on the submitted code, whether that is a full autograder package like ottr or just hidden assert statements from a file
- Can provide/display feedback based on what is wrong in the code (ie which test fails) and the correct solution

I'm imagining something like this:

![image](https://github.com/jupyterlite/jupyterlite/assets/4560057/31d379af-f6e7-4f9c-807e-1ac3e9726cdf)

That screenshot is from https://github.com/ines/course-starter-python which seems to not be actively maintained any longer, and I would prefer to use a more established framework such as Jupyter Book or Quarto together with something like quarto-webr or JupyterLite for the textbook. 

To what extent is something like this currently achievable with quarto-webr  (e.g. can I have tests run on the code each time a submit button is clicked?) and would this type of component be considered in scope for the project and likely to see development in the future or is it something that needs to happen more on the Quarto side of things?

**Comment by coatless** [comment]
It's on deck: https://github.com/coatless/quarto-webr/issues/121

We're looking to support a similar syntax to `{learnr}` to reduce the amount of porting required. So, we'll stack the `hint`/`solution`/et cetera on the code cell via labels. 

This wouldn't be an upstream request in `Quarto`; just a modification of the custom compute cell introduced in `quarto-webr`.

**Comment by joelostblom** [comment]
Awesome! Sorry I completely missed that issue when I went through the list. I will comment there instead and close this.
