### ISSUE TITLE
[Q&A]: License/Permission to adapt

### ISSUE THREAD

**Issue by trevorgunn** [coatless/quarto-webr#162]
### What's your question?

Hi,

I've been considering writing a Quarto extension to embed [SageMath cells](https://sagecell.sagemath.org/). They're similar to WebR but run on a remote server rather than through Wasm. I'm not going to start right now on this since we're mid-semester but perhaps as a summer project.

I was wondering if you would be willing to add a permissive license or otherwise agree to let me adapt some of your code here so I wouldn't be starting from scratch. I would be publishing my extension most likely under the MIT License.

**Comment by coatless** [comment]
@trevorgunn given that you need a binder backend, you probably want to stay tuned for some work I'm exploring with [`Thebe`](https://thebe.readthedocs.io/en/stable/) over in [`coatless-quarto/thebe`](https://github.com/coatless-quarto/thebe). At a glance, SageMath already has integration with `Thebe` through [`sage_package`](https://sage-package.readthedocs.io/en/latest/sage_package/thebe.html). 

Regarding licensing, I'm planning to use a copyleft license like AGPL over MIT after I land a few more features and clean up the project's backend.

**Comment by trevorgunn** [comment]
Thanks! Copyleft is fine by me.

I'll probably stick with SageMathCell over Thebe. It has a faster startup time and is better supported by the sagemath community. But I will stay tuned nonetheless.
