### ISSUE TITLE
[Bug]: Code boxes always show scroll bars even when the content is smaller than the box

### ISSUE THREAD

**Issue by WillemSleegers** [coatless/quarto-webr#164]
### Bug description

Not sure if this is the right place to mention this bug!

It seems that regardless of the amount of code, a code box always shows scroll bars when you hover over the box with the mouse. Using the scroll wheel you can also move the content in a box around slightly, even when the content is clearly smaller than the box.

### Steps to reproduce

I think this bug occurs for any code box. You can find an example here: https://willemsleegers.github.io/webr-guesstimate/

### Your environment

- IDE: VS Code Version: 1.87.0 (Universal)
- OS: macOS Sonoma 14.3.1

**Comment by coatless** [comment]
No worries, feel free to report any behavior that might seem amiss. So, the editor in the example looks like:

<img width="811" alt="Example as-is for scrollbar hiccup in Monaco Editor with interactive cell in {quarto-webr}" src="https://github.com/coatless/quarto-webr/assets/833642/ce6c8540-a7b7-43dd-9831-0328c10998d1">

Regarding the horizontal bar, the 2 lines in the cell slightly exceed the width causing the horizontal scroll bar to appear. Changing it slightly causes the lines to disappear:

<img width="804" alt="Example with modifications to remove horizontal scrollbar" src="https://github.com/coatless/quarto-webr/assets/833642/630af1c7-cb2b-4470-9d94-6407ee5b8934">

The vertical line is something I need to dig deeper to check.

**Comment by coatless** [comment]
To solve this issue, we need to add about 1 or 2 pixels to the adaptive content expansion:

https://github.com/coatless/quarto-webr/blob/62298630ba186e186bc7ff4ea05c213d01acd368/_extensions/webr/qwebr-monaco-editor-element.js#L62

This will be addressed alongside #177.

**Comment by coatless** [comment]
@WillemSleegers thanks again for the report. Just a heads up, this was fixed in 0.4.2-dev.2. We've also added a way to constrain the editor via `editor-max-height: <pixel-value>`

You can explore the fix in the following test:

https://quarto-webr.thecoatlessprofessor.com/tests/qwebr-test-editor-options.html#adaptive-container-constraints

**Comment by WillemSleegers** [comment]
Thanks for the fix!
