### ISSUE TITLE
[Q&A]: Error with `read.csv`

### ISSUE THREAD

**Issue by jonathan-taylor** [coatless/quarto-webr#174]
### What's your question?

I am unable to download files that I know are publicly readable [example](https://web.stanford.edu/class/stats191/data/schizophrenia.csv)

```{webr-r}
read.csv('https://web.stanford.edu/class/stats191/data/schizophrenia.csv', header=TRUE)
```

I get an error like: 

**
Access to XMLHttpRequest at 'https://www.stanford.edu/class/stats191/data/schizophrenia.csv' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
**

Is there a config I need to set for this request so that the server doesn't think it's "null"?

**Comment by jonathan-taylor** [comment]
Error above is in the JavaScript console.... doesn't appear in the HTML seen in the page.

**Comment by coatless** [comment]
Yup, the server in this case needs to enable Cross-origin resource sharing (CORS):

You can enable it just for data files with: 

```default
location ~* \.(csv|xls|txt)$ {
    add_header Access-Control-Allow-Origin *;
}
```

Or enable it globally with: 

```default
location / {
    add_header 'Access-Control-Allow-Origin' '*' always;
}
```

Perhaps the easiest way forward is to create a data-raw repo on GitHub and enable GitHub Pages as CORS is on by default, c.f. 

https://github.com/coatless/raw-data

https://coatless.github.io/raw-data/

**Comment by jonathan-taylor** [comment]
Thanks, made a github repo for data files. Works fine
________________________________
