### ISSUE TITLE
[Yet another feature]: Maximum height for editor window?

### ISSUE THREAD

**Issue by ute** [coatless/quarto-webr#177]
### Feature Description

The adaptive container for the editor window is really neat!

Does it makes sense to limit the height of the editor window sometimes?
I've patched this in to `qwebr-monaco-editor-element.js` for my purposes, via
```js
const maxheight = qwebrOptions['max-height']??1000;
const updateHeight = () => {
      const contentHeight = Math.min(editor.getContentHeight(), maxheight);
...
```
and set to 500 in yaml (think I will increase the default to 1000 and set the limit in yaml to 1000) 😊

**Comment by coatless** [comment]
@ute that would be a great option, but we need to be a little bit more conservative as there are quite a few code cells already taking advantage of auto-resizing in HTML documents vs. slides. 

To maintain backward compatibility, I think the best course would be to not enforce a cap if `editor-max-height` is unset. If it's set we'd then opt-in to using it. e.g. 

```js
const updateHeight = () => { 
         // if max-height is present, threshold. Otherwise, allow infinite growth.
         const contentHeight = qwebrOptions['max-height'] ? Math.min(editor.getContentHeight(), maxheight) : editor.getContentHeight();
```

**Comment by ute** [comment]
Perfect!
