### ISSUE TITLE
[Feature]:  Allow setting monaco editor's `quickSuggestions` argument

### ISSUE THREAD

**Issue by egenn** [coatless/quarto-webr#182]
### Feature Description

Thank you for the awesome extension.

It would be great to allow setting monaco editor's `quickSuggestions` argument, e.g. by adding 
`quickSuggestions: qwebrOptions['quick-suggestions'] ?? true` where editor is created in `qwebr-monaco-editor-element.js`.
I've tried this successfully, happy to open PR. 
I use it for developing exercises, where suggestions can be distracting.

**Comment by coatless** [comment]
@egenn sure! Let's go with an option of `editor-quick-suggestions: false`. Sound okay? 

PRs are welcome or I can patch it in as it'll be quick (~2 hours till back at a computer). Up to you.
