### ISSUE TITLE
[Q&A]: Using a webr-r code cell under Quarto's PDF render option

### ISSUE THREAD

**Issue by eli-daniels** [coatless/quarto-webr#192]
### Feature Description

Hi, for starters thanks heaps for creating this extension.

Currently rendering a quarto document with a webr code block shows only the input code and no output. Looking through the docs and experimenting with code cell options I can't see any options to make this possible, am I wrong?

Essentially I'm asking for PDF outputs to include webr code chunk outputs as well as inputs.

I know it sounds counter intuitive to want to use webr and have pdf (static) outputs. But I'm in a situation that requires a pdf download of the webpage to be available.

**Comment by coatless** [comment]
I think I'm missing something. If you try to print the following test suite page:

https://quarto-webr.thecoatlessprofessor.com/tests/qwebr-test-internal-cell.html

You should get:

<img width="1517" alt="Example printing of a quarto-webr enabled page with webR code and output cells displayed" src="https://github.com/coatless/quarto-webr/assets/833642/9e1ce7ea-a783-4375-8c21-5ffa1465dd37">

This page uses a combination of [`context: output` cells](https://quarto-webr.thecoatlessprofessor.com/qwebr-internal-cell.html#output---hidden-evaluation-with-results-shown) and the [`autorun: true`](https://quarto-webr.thecoatlessprofessor.com/demos/qwebr-auto-run.html) option.

Are you trying to snapshot the page using [`{webshot2}`](https://github.com/rstudio/webshot2)? Or are you trying to include the source within the `output` context?

**Comment by eli-daniels** [comment]
Hi, sorry to be clear, I am using `quarto::quarto_render(output_format = 'pdf')` to create the pdf document.

# Using these _quarto.yaml settings:

```(yaml)
project:
  title: "webr-pdf-test"
filters:
  - webr
editor: source
```


# And this index.qmd file:

```(yaml)
---
title: "webr-pdf-test"
---
```

## Quarto

Quarto enables you to weave together content and executable code into a finished document. To learn more about Quarto see <https://quarto.org>.

Regular R code chunk
```{r}
1 + 1
```

web-r code chunk, all options defaults
```{webr-r}
1 + 1
```

web-r code chunk, autorun: true
```{webr-r}
#| autorun: true 
1 + 1
```

web-r code chunk, autorun: true, context:output
```{webr-r}
#| autorun: true 
#| context: output
1 + 1
```


web-r code chunk, context:output
```{webr-r}
#| context: output
mat2x2 <- matrix(c(1, 2, 3, 4), nrow = 2)
mat2x2
```

# HTML output  is the following when using `quarto::quarto_render(output_format = 'html')` 

![image](https://github.com/coatless/quarto-webr/assets/90638398/d2ef5171-71f0-42e7-8872-1b15c00ff46f)


# PDF output is the following when using `quarto::quarto_render(output_format = 'pdf')` 

![image](https://github.com/coatless/quarto-webr/assets/90638398/15308c9a-c5b2-4c21-84e9-204b65a9c03d)

**Comment by coatless** [comment]
@eli-daniels thanks for the MWE. 

The `webr-r` cell is a custom code cell that only supports Quarto's HTML renderer (with minimal support for QMD -> MD -> HTML). So, this result is to be expected when used under the `pdf` output option since we fallback to display the cell "as-is".

Regarding the feature request, we cannot cause the `webr-r` cell to be evaluated as native R code if we detect the output mode of PDF as we're already pretty far down the process when we can work with the cell, c.f.

![image](https://github.com/coatless/quarto-webr/assets/833642/ea8b4f4c-152f-46ca-b2a6-dccd844e5d64)

So, the easiest way here would likely be creating a snapshot of the HTML page using [`{webshot2}`](https://github.com/rstudio/webshot2) or having students print the webpage as a PDF via the web browser. I know neither is an ideal solution; but, those are the options I see.

**Comment by eli-daniels** [comment]
Okay, fair enough.  I'll try to work something out with quarto's conditional content in this case.

Thanks for your time!

**Comment by coatless** [comment]
@eli-daniels for the [conditional content](https://quarto.org/docs/authoring/conditional.html) being mentioned, I think this means that two cells would need to be created:  

1. a code cell using `{r}` designation; and,
2. a code cell with the `{webr-r}` designation
 
Each must be "wrapped" in its own div body with the correct `when-format` specified.

For example, we would have:

````md
::: {.content-visible when-format="html"}

```{webr-r}
1 + 1
```

:::
::: {.content-visible when-format="pdf"}

```{r}
1 + 1
```

:::
````

(Jotting this note down for the future googler.)

**Comment by eli-daniels** [comment]
Hi @coatless, yep thats the method I used along with a script to 'copy/paste' each code block before output to pdf. The script uses readLines, writeLines and append, works quite well so far.
Cheers,

**Comment by coatless** [comment]
@eli-daniels thanks for the confirmation! I'm going to close out the Q&A now. 

If you want to share your script for others, please feel free to reply to the ticket. Otherwise, no worries!
