### ISSUE TITLE
[Q&A]: What is the difference between milestone '4.x' and, say, '4.2' and '4.3'?

### ISSUE THREAD

**Issue by HenrikBengtsson** [coatless/quarto-webr#199]
### What's your question?

I see there's a '4.x' milestone at <https://github.com/coatless/quarto-webr/milestones>, and it already has some issues closed.  What does that mean?  Will those issues be part of the next '4.2' milestone, or have you not yet decided?

PS. You can relabel milestones at anytime; may I suggest to re-label '4.2' to '4.2 (next release)' to make it easy to know which issues are part of the next release when you browse <https://github.com/coatless/quarto-webr/issues>.

**Comment by coatless** [comment]
@HenrikBengtsson thanks for the question! 

For milestones, the `4.x` line involves issue tickets that should be addressed eventually in the `4.x` series. 

Given the scope, sometimes they can be addressed quickly or we would need upstream features from webR to implement. Those closed tickets are already part of the current release cycle (4.2, #133,  #164) or were included previously (4.1, c.f. #124).  With closed tickets appearing under `4.x`, that's on me as I didn't update the milestone. I'll try to be clearer about that going forward.

**Comment by HenrikBengtsson** [comment]
Thanks - that makes sense.  I see you've moved those closed "4.x" to "4.1" and "4.2".  Thanks also for relabling to "4.2 (next release)" - hopefully that'll help us "outsiders".
