### ISSUE TITLE
ggplot graphs do not display

### ISSUE THREAD

**Issue by ethanwhite** [coatless/quarto-webr#2]
To reproduce quarto preview the following code:

    ---
    title: ggplot
    filters:
      - webr
    ---
    
    ```{r}
    library(ggplot2)
    ggplot(mtcars, aes(x = hp, y = mpg)) +
      geom_point()
    ```
    
    ```{webr}
    webr::install('ggplot2')
    ```
    
    ```{webr}
    library(ggplot2)
    ggplot(mtcars, aes(x = hp, y = mpg)) +
      geom_point()
    ```

Result:

The `{r}` block produces the expected plot. The `{webr}` block produces a white space of the appropriate size but it is just blank.

**Comment by coatless** [comment]
I think this is piggybacking off of #1 as the graphics output shared the same options. With that fix present, I'm getting: 

<img width="1230" alt="ggplot2-graph-displaying" src="https://user-images.githubusercontent.com/833642/224574005-73ddc11a-d85f-4c11-aa64-670d6096595f.png">

Though, the time to display a `ggplot2` is still a bit higher. I'm going to experiment with having the option to enable a local COOP & COEP header today to alleviate that.

**Comment by ethanwhite** [comment]
Yep - ggplot is working great now as well. Thank you!

**Comment by snhansen** [comment]
Working here as well - thanks! However, it takes 6-7 minutes to install all necessary packages on my laptop. It only takes 20 seconds or so at https://webr.gwstagg.co.uk/, so looking forward to see how much this can be reduced.

**Comment by coatless** [comment]
Short gist: If you control your own server, you may setup the HTTP header with:

```
Cross-Origin-Opener-Policy: same-origin
Cross-Origin-Embedder-Policy: require-corp
```

For nginx this looks like: 

```
location ^~ /directory/with/webr/content {
  add_header "Cross-Origin-Opener-Policy" "same-origin";
  add_header "Cross-Origin-Embedder-Policy" "require-corp";
}
```

https://github.com/coatless/quarto-webr#speed-up-webr

**Comment by snhansen** [comment]
It's still taking minutes for me. How long does it take for you to run the last code chunk on https://rd.thecoatlessprofessor.com/webR-quarto-demos/webr-quarto-html-demo.html? It seems to be making thousands of weird requests.
