### ISSUE TITLE
[Bug]: tidyverse/readr progress bar shows "gibberish" before description

### ISSUE THREAD

**Issue by ElijahMeyer3** [coatless/quarto-webr#206]
### Bug description

When reading in data by clicking Run Code, "gibberish" output is given before expected output. 

![webR_example](https://github.com/coatless/quarto-webr/assets/31972023/50beccde-b938-403c-a918-fdb22bfe2621)

### Steps to reproduce

The data are stored in a data folder in the same repo as the Bechdel + data visualization qmd.

````qmd
---
title: "Bechdel + data visualization"
order: 2
webr:
  packages: ['tidyverse', 'scales']
---

```{webr-r}
#| echo: false
bechdel <- read_csv("bechdel.csv")
```
````

### Your environment

RStudio 2023.12.1+402 
Windows 11

### Quarto check output

Quarto 1.4.530 
Pandoc version 3.1.11
Dart Sass version 1.69.5
Deno version 1.37.2

Quarto installation
Version: 1.4.530

**Comment by coatless** [comment]
Couple of quick clarifying statements:

1. I think this is the data:

https://github.com/ElijahMeyer3/Coursera/blob/main/bechdel.csv

2. Is the "gibberish" output the following: 

```
[1mindexing[0m [34mbechdel.csv[0m [====================================] [32m109.28MB/s[0m, eta: [36m 0s[0m
```

Or is it that `echo: false` didn't suppress the standard output? 

--- 

For the cell suppression, we only have limited support for disabling STDERR messages (red text) via `messages: false` or `warnings: false`. c.f. [Code Cell Options](https://quarto-webr.thecoatlessprofessor.com/qwebr-cell-options.html#cell-output). We don't currently implement an `echo: false` option. 

For the progress bar, I think that's related to `{readr}`/`{rlang}` showing a progress bar while not being _exactly_ in an interactive mode. The gibberish that is generated is a side effect of not being able to reset a writing buffer. We need to handle this part upstream at `webR` (set a non-interactive flag under our use of [`captureR`](https://docs.r-wasm.org/webr/latest/evaluating.html#evaluating-r-code-and-capturing-output-with-capturer)) and/or tweak detection in [`readr::show_progress()`](https://github.com/tidyverse/readr/blob/e529cb2775f1b52a0dfa30dabc9f8e0014aa77e6/R/utils.R#L24)/[`rlang::is_interactive()`](https://github.com/r-lib/rlang/blob/ae49b53891fdd340df3a54200481f50752345d29/R/state.R#L111). 

The quickest way forward would be to set in a setup context:

````md
```{webr-r}
#| context: setup
# Disable progress bar
options(readr.show_progress = FALSE)
```
````

Or, within the above code cell using:

````md
```{webr-r}
bechdel <- read_csv("bechdel.csv", progress = FALSE)
```
````

**Comment by ElijahMeyer3** [comment]
Thank you for the clarification questions. 

The "gibberish" output is indeed the 
```
[1mindexing�[0m �[34mbechdel.csv�[0m [====================================] �[32m109.28MB/s�[0m, eta: �[36m 0s�[0m
```

That is the data we are using. However, that isn't the location. The exercise is in a private repo. Within the repo, we have a data folder and the data set lives there.

This issue isn't specific to this data set. I see this issue across any data set I try and read in this way.

**Comment by ElijahMeyer3** [comment]
> Couple of quick clarifying statements:
> 
> 1. I think this is the data:
> 
> https://github.com/ElijahMeyer3/Coursera/blob/main/bechdel.csv
> 
> 2. Is the "gibberish" output the following:
> 
> ```
> [1mindexing�[0m �[34mbechdel.csv�[0m [====================================] �[32m109.28MB/s�[0m, eta: �[36m 0s�[0m
> ```
> 
> Or is it that `echo: false` didn't suppress the standard error output?
> 
> For the cell suppression, we only have limited support for disabling STDERR messages (red text) via `messages: false` or `warnings: false`. c.f. [Code Cell Options](https://quarto-webr.thecoatlessprofessor.com/qwebr-cell-options.html#cell-output). We don't currently implement an `echo: false` option.
> 
> For the progress bar, I think that's related to `{readr}`/`{rlang}` showing a progress bar while not being _exactly_ in an interactive mode. The gibberish that is generated is a side effect of not being able to reset a writing buffer. We need to handle this part upstream at `webR` (set a non-interactive flag under our use of [`captureR`](https://docs.r-wasm.org/webr/latest/evaluating.html#evaluating-r-code-and-capturing-output-with-capturer)) and/or tweak detection in [`readr::show_progress()`](https://github.com/tidyverse/readr/blob/e529cb2775f1b52a0dfa30dabc9f8e0014aa77e6/R/utils.R#L24)/[`rlang::is_interactive()`](https://github.com/r-lib/rlang/blob/ae49b53891fdd340df3a54200481f50752345d29/R/state.R#L111).
> 
> The quickest way forward would be to set in a setup context:
> 
> ```
> ```{webr-r}
> #| context: setup
> # Disable progress bar
> options(readr.show_progress = FALSE)
> ```
> ```
> 
> Or, within the above code cell using:
> 
> ```
> ```{webr-r}
> bechdel <- read_csv("bechdel.csv", progress = FALSE)
> ```
> ```

This is perfect. Thank you!

**Comment by ElijahMeyer3** [comment]
[heart]         Elijah Meyer, Ph.D. reacted to your message:
________________________________

**Comment by coatless** [comment]
George modified `Shelter.captureR()` in the latest webR build so that non-interactive status at the R level has now been set. This should mean that in webR v0.3.4 or v0.4.0 the need to disable progress via a setup cell is no longer required.

**Comment by ElijahMeyer3** [comment]
[celebrate]     Elijah Meyer, Ph.D. reacted to your message:
________________________________
