### ISSUE TITLE
[Q&A]: License

### ISSUE THREAD

**Issue by arnaud-feldmann** [coatless/quarto-webr#220]
### What's your question?

Hi,
I'm using your extension in a R tutorial for my coworkers : https://github.com/arnaud-feldmann/formation_r_drieets_prog_fonctionnelle/
I'm willing to respect your rights. However, I don't know how to because there's no LICENSE file inside your repository.
What's the recommended way to use your extension ?

Should I add it at rendering time within the github action (hence no copy of your repo is made) ? Or distributing your extension inside the _extension folder is ok (if so, maybe putting a license file of yours somewhere could be fine) ?

Thanks for your very useful work,

Arnaud FELDMANN

**Comment by coatless** [comment]
Thanks for letting me know! 

You might want to opt for the official Quarto WebAssembly backend that was just open-sourced: [quarto-live](https://github.com/r-wasm/quarto-live)!
