### ISSUE TITLE
[Q&A]: Choose the version of R?

### ISSUE THREAD

**Issue by eusebe** [coatless/quarto-webr#225]
### What's your question?

My questions might seem obvious, but I couldn't find the answers in your documentation (which is very clear and detailed, by the way :-)). The version of R available when using the quarto-webr extension is 4.4.1, both in the course materials I generate and in the documentation for the extension:
![image](https://github.com/user-attachments/assets/65448049-c367-4529-bed3-733d985df951)

However, on the webr website, the available R version is more recent (4.4.2):

![image](https://github.com/user-attachments/assets/7112c9cc-28e5-485e-a02d-4971116e7a28)

So, my questions are:

1) Is it possible to *use the latest* version of R with the quarto-webr extension?
2) Is it possible to *select the R version* through an option in this extension?

Thank you very much in advance!

**Comment by coatless** [comment]
> 1. Regarding using the latest version of R with the quarto-webr extension:

Yes, it's possible to use the latest available R version through webR by specifying `"latest"` as the version in your configuration. However, it's important to understand that you'll get the latest R version that's available within webR, not necessarily the absolute latest R release.

> 2. Regarding selecting specific R versions:

The R version is tied directly to the webR version you specify - you can't select an R version independently. Instead, you select a webR version, and that determines which R version you'll get. You would set this in your `_quarto.yml` or `.qmd` file like:

```yaml
webr:
  version: 0.4.2  # Gets you the R version bundled with webR 0.4.2 (e.g. R 4.4.1)
```

or

```yaml
webr:
  version: "latest"  # Gets you the R version bundled with the latest webR
```

Check the webR project release notes for any kind of R version bumps: 

https://github.com/r-wasm/webr/releases

**Comment by eusebe** [comment]
Thanks!
