### ISSUE TITLE
Preload objects/functions

### ISSUE THREAD

**Issue by aloy** [coatless/quarto-webr#25]
This is likely my misunderstanding, but is there a way to set `echo: false` as in usual quarto docs and have the code executed? For example, if I wanted to create a homework checker I would want the first chunk in the background and the second to show to the user.

Thanks!

```{webr-r}
#| echo: false
answer_frame <- data.frame(
  problem = c("1a", "1b", "2"),
  answer = c(10, 2, 3/16),
  tol = c(0.001, 0, 1/32)
)

check <- function(problem, answer) {
  aframe <- answer_frame
  if(!problem %in% aframe$problem) stop("Please enter a valid problem.")

  solution <- aframe[which(aframe$problem == problem), "answer"]

  ifelse(
    all.equal(answer, solution, tolerance = 0.001) == TRUE,
              "Correct",
              "Incorrect")
}
```

```{webr}
check(problem = "1a", answer = 11)
```

**Comment by coatless** [comment]
@aloy thanks for the question. Unfortunately, we can't support the `echo: false` portion as we need the code cell to propagate through until the Lua filter.

The workaround for this right now is given in https://github.com/coatless/quarto-webr/issues/9#issuecomment-1475815799 with an RFC in #11 for future functionality. Feel free to provide comments about the wording.

**Comment by coatless** [comment]
Also, any piece of code you make available to students, they _will_ be able to see if they inspect the HTML page source. Thus, `quarto-webr` should **not** be used for formal assessment as the answers would be readable inside the HTML page source.

**Comment by coatless** [comment]
This feature is now available in the development version of `quarto-webr`.  You can obtain a copy by typing into terminal:

```sh
quarto add coatless/quarto-webr
```

We've added your example into a test document as well. Please let us know if you would like to be credited (name, email?)

https://github.com/coatless/quarto-webr/blob/main/webr-internal-cell.qmd

<img width="931" alt="Demo of Hidden Code Cell" src="https://github.com/coatless/quarto-webr/assets/833642/8909eccb-a924-43a9-b008-e2df76d20673">
