### ISSUE TITLE
Cannot reproduce minimal example

### ISSUE THREAD

**Issue by JosiahParry** [coatless/quarto-webr#26]
Following the minimal example results in the following error:

```
Error running filter /Applications/quarto/share/filters/main.lua:
Error running filter /Users/josiahparry/github/jebby/webr:
Could not find executable /Users/josiahparry/github/jebby/webr
stack traceback:
        /Applications/quarto/share/filters/main.lua:4030: in function </Applications/quarto/share/filters/main.lua:4009>
        [C]: in ?
        [C]: in method 'walk'
        /Applications/quarto/share/filters/main.lua:171: in function 'run_emulated_filter'
        /Applications/quarto/share/filters/main.lua:449: in local 'callback'
        /Applications/quarto/share/filters/main.lua:454: in upvalue 'run_emulated_filter_chain'
        /Applications/quarto/share/filters/main.lua:495: in function </Applications/quarto/share/filters/main.lua:476>
stack traceback:
        /Applications/quarto/share/filters/main.lua:171: in function 'run_emulated_filter'
        /Applications/quarto/share/filters/main.lua:449: in local 'callback'
        /Applications/quarto/share/filters/main.lua:454: in upvalue 'run_emulated_filter_chain'
        /Applications/quarto/share/filters/main.lua:495: in function </Applications/quarto/share/filters/main.lua:476>
```

Are there additional steps to the installation other than ensuring webR are installed via `npm i webR` and adding the quarto filter?

**Comment by coatless** [comment]
So, I'm unable to reproduce an error like this using one of the example/test documents in the repository.

A few questions:

1. What is the minimal example being used? 
2. What version of Quarto is being used? 
3. Are you using the Quarto to VS Code extension or RStudio client? What versions are those extensions/clients at?
4. Are you using knitr or python as the compute engine? 
5. What is your operating system version information?

[![Open in GitHub Codespaces](https://github.com/codespaces/badge.svg)](https://codespaces.new/coatless/quarto-webr)

**Comment by JosiahParry** [comment]
1.  The example from the README
````
---
title: webR in Quarto HTML Documents
format: html
engine: knitr
filters:
  - webr
---

This is a webr-enabled code cell in a Quarto HTML document.

```{webr-r}
fit = lm(mpg ~ am, data = mtcars)
summary(fit)
```
````
2. 1.3.450
3. Quarto in RStudio and VS Code reproduce the same issue
4. Using the knitr engine as it is specified in the yaml front matter 
5. Apple M1 with Ventura 13.3

**Comment by coatless** [comment]
Thanks, that's very useful!

So, what's going on here is the `webr` filter is missing from the `_extension` directory that resides next to where the `.qmd` document should be.

In particular, we want a folder structure like:

```sh
.
├── _extensions
│   └── coatless
│       └── webr
│           ├── _extension.yml
│           ├── ...
│           └── webr.lua
├── test-document.qmd
├── webr-serviceworker.js
└── webr-worker.js
```

So, if you change directory to where the `.qmd` file is, then you can add the `webr` quarto filter by typing into Terminal:

```sh
quarto add coatless/quarto-webr
```

Here's a quick walkthrough video showing the `_extension` folder next to where the `.qmd` document is:

![ensure-quarto-filter-present-next-to-document](https://github.com/coatless/quarto-webr/assets/833642/388f7a71-f3c5-41e1-bf5d-c975a3650717)

**Comment by JosiahParry** [comment]
Simple pathing problem. Thank you <3
