### ISSUE TITLE
webR not loaded in rendered html

### ISSUE THREAD

**Issue by snhansen** [coatless/quarto-webr#3]
When previewing using `quarto preview` webR-blocks are loaded fine. However, when I just load the html file in my browser, the blocks aren't loading (they stall at "Loading webR..."). Debugger shows this:

![image](https://user-images.githubusercontent.com/45770265/224652958-62e87ce7-bd31-4f2b-afec-2fc37445107a.png)

Minimal example below:

	---
	format: html
	filters:
	  - webr
	engine: knitr
	---

	```{webr}
	1+1
	```

**Comment by snhansen** [comment]
Here's what it looks like from Chrome:

![image](https://user-images.githubusercontent.com/45770265/224661149-76945f1c-54b3-4f61-bda9-0ac1fa45b248.png)

**Comment by coatless** [comment]
When using  `quarto preview`, the rendered HTML document is being shown by mimicking a server running under `https://localhost/`. Thus, the worker files that we use are able to be loaded with either the `http://` or `https://` protocol.  However, if you open the rendered `.html` file as-is (not in a server context), the outcome is the browser tries to use `file:///`. This is a security restriction surrounding the origin and relative location. 

You can read a bit more about it in this StackOverflow answer:

https://stackoverflow.com/questions/6811398/html5-web-workers-work-in-firefox-4-but-not-in-chrome-12-0-742-122/6823683#6823683

To get around this, you can try one of these options: 

- [Use Chrome's `--allow-file-access-from-files` access](https://stackoverflow.com/questions/18586921/how-to-launch-html-using-chrome-at-allow-file-access-from-files-mode)
- [Use the WebServer for Chrome extension](https://chrome.google.com/webstore/detail/web-server-for-chrome/ofhbbkphhbklhfoeikjpcbhemlocgigb?hl=en)
- Or, [use NPM to obtain `local-web-server`](https://github.com/lwsjs/local-web-server)

**Comment by snhansen** [comment]
Aha, didn't know that. Thanks for the explanation and sorry about the "issue".

**Comment by coatless** [comment]
No worries. The "issue" turns out to be a great item for the "Known Hiccups" section of the `README.md`.
