### ISSUE TITLE
Improving the UI of the Code Cell

### ISSUE THREAD

**Issue by coatless** [coatless/quarto-webr#47]
The UI of the code cell currently looks like this: 

<img width="772" alt="quarto-webr code cell" src="https://github.com/coatless/quarto-webr/assets/833642/31c91622-447d-4036-87d5-98f972126fbb">

We had a few comments about improving the cell to be more like `learnr` and other notebook interfaces...

**Comment by coatless** [comment]
## learnr

Uses ACE

**Without solutions**

<img width="440" alt="learnr without solutions interface" src="https://github.com/coatless/quarto-webr/assets/833642/584c4bab-5b3f-4368-889f-2062010b24ec">

**With Solutions**

<img width="476" alt="learnr with solutions interface" src="https://github.com/coatless/quarto-webr/assets/833642/427eb9b0-1173-4cdb-865a-30cca48de160">

## The School of Data

Uses Code Mirror

**Ready state code cell**

<img width="433" alt="The School of Data's Code Cell" src="https://github.com/coatless/quarto-webr/assets/833642/e9bf902d-793a-4fc0-86c7-1d9f8be3791e">

**Loading code cell**

<img width="91" alt="The School of Data's Loading UI" src="https://github.com/coatless/quarto-webr/assets/833642/89e84d69-920d-478a-b89d-85c4e861b137">

## RStudio

**Source**

<img width="682" alt="RStudio's Notebook Source Run Controls" src="https://github.com/coatless/quarto-webr/assets/833642/3cbda9bc-064d-4b20-b1f2-a0c44e5a2467">

**Runtime**

<img width="453" alt="RStudio's Notebook Visual Editor Run Controls" src="https://github.com/coatless/quarto-webr/assets/833642/5148445f-1dac-4dfa-8b18-5988dacead08">

**Main bar**

<img width="696" alt="Main RStudio Bar" src="https://github.com/coatless/quarto-webr/assets/833642/7629c4d3-697a-4108-9aad-5b228db50cda">

Options

<img width="293" alt="RStudio Options" src="https://github.com/coatless/quarto-webr/assets/833642/8edb64f9-d05f-4957-bde4-57617a584394">

## VS Code

**In-line cells**
<img width="205" alt="VS Code Interface inline" src="https://github.com/coatless/quarto-webr/assets/833642/5728b64b-7d69-4001-a8f9-ac50360729f7">

**Play button**
<img width="297" alt="VS Code Interface play button" src="https://github.com/coatless/quarto-webr/assets/833642/c0174c0f-06e6-4435-bb44-6a59e379a241">


## Colab

<img width="887" alt="Colab cell" src="https://github.com/coatless/quarto-webr/assets/833642/bb68fb54-dbb2-4d3a-b0e0-992f54b26578">

## JupyterLab

<img width="373" alt="JupyterLab Notebook Controls" src="https://github.com/coatless/quarto-webr/assets/833642/9bec112e-9c51-48c3-ae4c-3397c5d02719">

**Comment by jimjam-slam** [comment]
I would be very excited about a 'Start over' button! This may be out of scope, but the ability to define several buttons (or a menu) for replacing the code in the box—or simply appending to it—would be great. I often run exercises where I'd like to make several potential suggestions but want to encourage students to explore and try things out.

On the aesthetic side, you could also hook into the CSS variables Quarto makes available for theming (basically the [SCSS variables](https://quarto.org/docs/output-formats/html-themes.html#sass-variables) but with `--quarto-` prefixed when they become CSS variables) to make it easy for end-users to tweak the appearance. I would personally prefer something fairly structurally minimal that users can experienced with CSS can override, but that's just my taste!

**Comment by coatless** [comment]
The startover feature is likely to come soon.  

On the note of customization, we'll probably support logic for turning on and off different parts in the revised menu bar. Though, I'm likely going to try to avoid the dropdown menu approach taken by RStudio's option panel/VS Code's component. Would having a [tabset panel](https://quarto.org/docs/output-formats/html-basics.html#tabsets) with different versions of the editor be a better UX for exploring suggestions? Some examples in that light would be a re-rendered ["choose your model adventure"](https://github.com/coatless-r-n-d/rmarkdown-multiverse-dynamic-code-chunks-and-tabs) or the following:


![tab-panel-multi-editors](https://github.com/coatless/quarto-webr/assets/833642/d775c805-62d3-48af-9476-701f061ad7d0)

On the aesthetic side, I opened a question on the best practices for enabling extension styling: 

https://github.com/quarto-dev/quarto-cli/discussions/7094

**Comment by jimjam-slam** [comment]
Oh yeah, a tabset makes a lot of sense! Much easier to implement 😅

**Comment by coatless** [comment]
@jimjam-slam code for the above tabset would be:

````md

---
title: webR in Quarto HTML Documents
format: html
engine: knitr
filters:
  - webr
---

This is a webr-enabled code cell in a Quarto HTML document.

::: {.panel-tabset}


## Say Hi

```{webr-r}
print("Hello quarto-webr World!")
```

## Calculate


```{webr-r}
-3 + 5
```


## Fit a Model

```{webr-r}
fit = lm(mpg ~ wt, data = mtcars)

summary(fit)
```

::: 

````

**Comment by jimjam-slam** [comment]
Thanks v much!

**Comment by coatless** [comment]
@jimjam-slam 

We're adding in the following CSS classes (Excuse the horrible CSS border usage.): 

<img width="1240" alt="annotated-qwebr-interactive" src="https://github.com/coatless/quarto-webr/assets/833642/3b08caef-cc0a-4c48-8208-a0156644e0da">

We'll likely add a box-shadow around the `qwebr-interactive-area` when it comes to RevealJS presentations.

**Comment by jimjam-slam** [comment]
Looks sick! Thank you!

**Comment by coatless** [comment]
Going to close out this issue for now as we made quite a few improvements in the later parts of the 3.x line. There are still more to come; but, the crux of the structure has been set.
