### ISSUE TITLE
Tracking Updates to Outdated Versions of `quarto-webr` Extension in Active Projects

### ISSUE THREAD

**Issue by coatless** [coatless/quarto-webr#49]
This issue serves as a tracking mechanism for monitoring the Pull Requests (PRs) directed towards active projects that are using outdated versions of the `quarto-webr` extension.

Feeling inundated with these PRs? Just write a comment below and we'll avoid sending a PR in the future.

## Active PR list

TBA

### 9/23 PRs to upgrade to v0.3.6

Our rationale behind selecting v0.3.2 is twofold:

1. **Latest R Compatibility:** Version v0.3.2 is chosen as it integrates seamlessly with the most recent version patched version of R 4.3.

2. **webR Alignment:** This version is also aligned with the latest release of webR (v0.2.1), promoting consistency and stability within the ecosystem.

#### Response

<details>
<summary>PRs sent 9/23 to upgrade to v0.3.6</summary>

- https://github.com/DanielEWeeks/HuGen2071/pull/1
- https://github.com/JavOrraca/quarto-blog/pull/31
- https://github.com/JamesHWade/jameshwadedotcom/pull/4
- https://github.com/jurjoroa/hcc-website/pull/1
- https://github.com/bluegreen-labs/R_book_template/pull/2

</details>

#### Non-response

<details>
<summary>Nonresponse PRs sent 9/23 to upgrade to v0.3.6</summary>

- https://github.com/swhawes/abcd-biostatwg-longitudinal/pull/5
- https://github.com/eteitelbaum/dataviz-fall-2023/pull/1
- https://github.com/djnavarro/quarto-blog/pull/125

</details>

## No upgrades list 

<details>
<summary>No upgrades users</summary>

- swhawes
- eteitelbaum
- djnavarro
</details>

## Misc

We found these public use cases by searching GitHub for:

```
_extensions/coatless/webr/_extension.yml
```

https://github.com/search?q=_extensions%2Fcoatless%2Fwebr%2F_extension.yml&type=code

From there, we extract the version key.

**Comment by khufkens** [comment]
Thanks for this fix! Much appreciated !!

**Comment by coatless** [comment]
Going to close this issue out as we'll likely setup a new one in the next month.

**Comment by khufkens** [comment]
Thanks, sorry for not following up on this. Will try to catch up myself.
