### ISSUE TITLE
Backticks have to be escaped in webr chunks

### ISSUE THREAD

**Issue by matt-dray** [coatless/quarto-webr#5]
Thank you for your work to bring webR to Quarto.

It seems you have to escape backslashes in a webr chunk. I was expecting webr chunks to behave like normal R chunks in this regard. I assume this is a parsing issue?

Below is an example webr chunk that uses lambda syntax. The screenshot shows the resulting error after 'Run code' is pressed. Note that the backslash hasn't appeared in the rendered chunk.

````
```{webr}
add_one <- \(x) x + 1
add_one(2)
```
````

![image](https://user-images.githubusercontent.com/18232097/225697535-6472a1c0-d183-4e12-9f47-0df9a1fdb86b.png)

Required fix:

````
```{webr}
add_one <- \\(x) x + 1
add_one(2)
```
````

![image](https://user-images.githubusercontent.com/18232097/225697929-014a462c-ac76-4f26-8e1d-e21b1c6b07f0.png)

**Comment by coatless** [comment]
Thanks! This should work now. Please re-install the extension: 

```sh
quarto add coatless/quarto-webr
```

Added it as an example in the `webr-demo.qmd` file: 

https://github.com/coatless/quarto-webr/blob/2f73a787acb2e5ed36f242d1cbb1f030c5528af8/webr-demo.qmd#L88-L93
