### ISSUE TITLE
[Q&A]: Data from Github

### ISSUE THREAD

**Issue by jgeller112** [coatless/quarto-webr#51]
### How to read data from Github

Hi, 

I just found this and am loving it. I want to read in a dataset from Github, but it hangs for a long time and does not download read the file. Any suggestions for getting this to work?

```

bb2021 <- read_csv("https://raw.githubusercontent.com/mllewis/cumulative-science/master/static/data/bb_2021_hr_clean.csv")

```

**Comment by coatless** [comment]
A couple of options:

1. Use the base R function instead of the `tidyverse`'s `read_csv()`.

```r
bb2021 <- read.csv("https://raw.githubusercontent.com/mllewis/cumulative-science/master/static/data/bb_2021_hr_clean.csv")
```

Any feature requiring a package will have a slightly longer startup since the packages must download. (Once per page visit.)

2. Switch the communication channel type over to `shared-array-buffer` by setting `channel-type` option. Note, that you must also ensure the COOP & COEP headers can be set. This usually requires deploying with Netlify.

```
---
title: My lecture ... 
webr:
  channel-type: "shared-array-buffer"
filters:
- webr
---
```

https://quarto-webr.thecoatlessprofessor.com/webr-communication-channels.html#sec-shared-array-buffer

**Comment by jgeller112** [comment]
Thank you for the fast response!

**Comment by jgeller112** [comment]
> @jgeller112 thanks for the question:
> 
> A couple of options:
> 
> 1. Use the base R function `read.csv()` instead of the `tidyverse`'s `read_csv()`.
> 
> ```r
> bb2021 <- read.csv("https://raw.githubusercontent.com/mllewis/cumulative-science/master/static/data/bb_2021_hr_clean.csv")
> ```
> 
> Any feature requiring a package will have a slightly longer startup since the packages must download. (Once per page visit.)
> 
> 2. Switch the communication channel type over to `shared-array-buffer` by setting `channel-type` option. Note, that you must also ensure the COOP & COEP headers can be set. This usually requires deploying with Netlify.
> 
> ```
> ---
> title: My lecture ... 
> webr:
>   channel-type: "shared-array-buffer"
> filters:
> - webr
> ---
> ```
> 
> https://quarto-webr.thecoatlessprofessor.com/webr-communication-channels.html#sec-shared-array-buffer

Students have been telling me that their code chunks will not load even though I am on the page running things with them. Is this related to that?

**Comment by coatless** [comment]
So, there are a variety of factors that can influence the load time for students. Without knowing a bit more, I'll be shooting in the dark. 

That said, if the page has multiple packages, e.g. `ggplot2` and `dplyr`, there will be a load time of about 2 minutes under `"service-worker"` or `"post-message"` channel types. If it's possible to set the HTTP headers for COEP & COOP to `"shared-array-buffer"`, you'll notice an immediate speed up. 

You can see some timing benchmarks here: 

https://observablehq.com/@hrbrmstr/webr-package-install-library-times

Please create a new ticket in the future as I might not see old/closed ticket messages.

**Comment by jgeller112** [comment]
Sorry. Will do. 

As an example: https://psy503-f2023.netlify.app/class_notes/06/06-samp_uncert. This run on one browser, but when I open another one it will not work.

**Comment by coatless** [comment]
@jgeller112 Feel free to open a bug ticket on that. It would help to know more specifics (e.g. browser versions & if extensions are enabled)
