### ISSUE TITLE
[Q&A]: Adding web-r to slides

### ISSUE THREAD

**Issue by jgeller112** [coatless/quarto-webr#52]
### Adding web-r to slides

Hello, 

I am following this presentation: https://teaching-with-webr.netlify.app/#/adding-webr-to-teaching-materials-1. I am trying to add web-r into my slides for class. Below is the header: 

```
title: "Monsters and Models"
subtitle: "Princeton University"
author: "Jason Geller, PH.D."
date: 'Updated:`r Sys.Date()`'
footer: "PSY 503: Foundations of Statistics in Psychology"
format: 
  revealjs:
    theme: blood
    multiplex: true
    transition: fade
    slide-number: true
    incremental: false 
    chalkboard: true
    fontsize: "25pt"
filters:
  - webr
execute:
  freeze: auto
  echo: true
  message: false
  warning: false
  fig-align: center
  fig-width: 12
  fig-height: 8
  editor_options: 
  chunk_output_type: inline
  code-overflow: wrap
  html:
    code-fold: true
    code-tools: true

```
In the presentation itself I am getting a loading webr-chunk. 

Any ideas what I can do to make this work?

**Comment by coatless** [comment]
Short version: Soon (TM). 

Long version: See the conversation in #14.

**Comment by jgeller112** [comment]
Thanks for linking to the post. I downgraded my webr as recommended, but get lua errors. I guess I will wait until the update.
