### ISSUE TITLE
"Loading webR" issue

### ISSUE THREAD

**Issue by eteitelbaum** [coatless/quarto-webr#6]
Hi, I am experiencing the "known hiccup" with "Loading WebR" displaying instead "Run Code". 

I checked and both the webr-worker.js and webr-serviceworker.js files are showing up in the project directory with the quarto document I am trying to render. 

Here is the code chunk I am trying to use webr for. 

````{webr}
dem_summary <- dem_women |> 
  group_by(region)  |> 
  summarize(
    polyarchy = mean(polyarchy, na.rm = TRUE),
    gdp_pc = mean(gdp_pc, na.rm = TRUE), 
    flfp = mean(flfp, na.rm = TRUE), 
    women_rep = mean(women_rep, na.rm = TRUE)
  ) |> 
  arrange(desc(polyarchy)) 

dem_summary
````
Here is the [rendered site](https://dataviz-gwu.rocks/modules/module-1.2.html) I am working on and [here](https://github.com/eteitelbaum/dataviz-summer-2023/edit/main/modules/module-1.2.qmd) is related code in my GitHub repo. Thanks!

**Comment by coatless** [comment]
@eteitelbaum what I'm seeing in console on the [rendered site](https://dataviz-gwu.rocks/modules/module-1.2.html) is: 

<img width="963" alt="web-console-error" src="https://user-images.githubusercontent.com/833642/226160396-6b1edf51-4abe-47d6-b070-a0c52c53722c.png">

```
module-1.2.html:1 Uncaught (in promise) TypeError: Failed to register a 
ServiceWorker for scope ('https://dataviz-gwu.rocks/modules/') with script 
('https://dataviz-gwu.rocks/modules/webr-serviceworker.js'): 
A bad HTTP response code (404) was received when fetching the script.

Failed to load resource: the server responded with a status of 404 ()
````


Manually checking the URLs:

- https://dataviz-gwu.rocks/modules/webr-serviceworker.js
- https://dataviz-gwu.rocks/modules/webr-worker.js

I see:

<img width="1071" alt="missing-files-in-location-netlify-warning" src="https://user-images.githubusercontent.com/833642/226160194-3ef68355-e39b-401f-af2b-e4ce977b3365.png">

I don't think the files are being copied into the `module` directory.

Could you create `zzz.qmd` file in the `module/` directory that contains: 

```
---
title: "Additional Dependencies"
format: html
---

1. [/modules/webr-serviceworker.js](/modules/webr-serviceworker.js)
2. [/modules/webr-worker.js](/modules/webr-worker.js) 
```

Let me know if that addresses the issue.

**Comment by eteitelbaum** [comment]
Hi @coatless, 

Now the code runs but I get an error that it can't find the `dplyr` functions in the code. I guess I got confused about what you were saying about "available packages" in the documentation. I thought that "available packages" meant that the ones in the list had already been installed in `webr`, but I suppose that was incorrect and now I need to run `webr::install("dplyr")`. Is that right?

But when I do that I get the following error: "Error: 'install' is not an exported object from 'namespace:webr'". What am I missing here? 

Thanks!

**Comment by coatless** [comment]
So, `webR` is not a 1-to-1 copy of `R` as we know it. It's a subset of the `R` ecosystem with its own package repository. The base _R_ packages are available by default. Other parts of the ecosystem, like `dplyr`, `ggplot2`, or the `tidyverse` are present only after being installed on a per-session basis. In _R_ terms, think of this like:

Local computer 

```r
# Call once to install permanently
install.packages("ggplot2")

# Load once for each session
library(ggplot2)
```


webR-enabled session: 

```r
# Call once for each webR session 
install.packages("ggplot2")

# Load on each R session
library(ggplot2)
```

The `webr::install()` function is part of the `webr` package. This package is embedded in the webR setup. Thus, if you attempt to run `webr::install()` outside of the `webR` code cell, you'll end up getting an error. 

So, modifying the Module 1.2 example, we have: 

```r
# Install once per webR session
webr::install("dplyr")

# Load the library 
library("dplyr")

# Desired code
dem_summary <- dem_women |> 
  group_by(region)  |> 
  summarize(
    polyarchy = mean(polyarchy, na.rm = TRUE),
    gdp_pc = mean(gdp_pc, na.rm = TRUE), 
    flfp = mean(flfp, na.rm = TRUE), 
    women_rep = mean(women_rep, na.rm = TRUE)
  ) |> 
  arrange(desc(polyarchy)) 

#write_csv(dem_summary, "data/dem_summary.csv")

dem_summary
```

The outcome is:

```r
Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

Error: object 'dem_women' not found
```

Note, the above code cell does not _load_ `dem_women`.  Thus, we have an error.

<img width="584" alt="outcome-base-r-coding" src="https://user-images.githubusercontent.com/833642/226197703-6dac1fac-bf69-470d-a01d-aaf58a750b75.png">

**Comment by eteitelbaum** [comment]
Thanks! What is the way to get data to run the code off of then? I tried adding lines to install packages and read the data from a .csv file but it didn't work. I am guessing `webr` cannot find the data on my local hard drive... 

```{webr}
webr::install(c("dplyr", "readr"))

library(dplyr)
library(readr)

dem_summary <- read_csv("data/dem_summary.csv")

dem_summary <- dem_women |> 
  group_by(region)  |> 
  summarize(
    polyarchy = mean(polyarchy, na.rm = TRUE),
    gdp_pc = mean(gdp_pc, na.rm = TRUE), 
    flfp = mean(flfp, na.rm = TRUE), 
    women_rep = mean(women_rep, na.rm = TRUE)
  ) |> 
  arrange(desc(polyarchy)) 

dem_summary
```

**Comment by eteitelbaum** [comment]
@coatless, Is there a solution, then? Can `webr` read local files or is there some other way to load the data? I tried adding a line of code to load the data frame from a local .csv file but it does not work. Thanks.

```r
webr::install(c("dplyr", "readr"))

library(dplyr)
library(readr)

dem_women <- read_csv("data/dem_women.csv")

dem_summary <- dem_women |> 
  group_by(region)  |> 
  summarize(
    polyarchy = mean(polyarchy, na.rm = TRUE),
    gdp_pc = mean(gdp_pc, na.rm = TRUE), 
    flfp = mean(flfp, na.rm = TRUE), 
    women_rep = mean(women_rep, na.rm = TRUE)
  ) |> 
  arrange(desc(polyarchy)) 

dem_summary
```
