### ISSUE TITLE
[Bug]: webr not loading when multiple people accessing web page

### ISSUE THREAD

**Issue by jgeller112** [coatless/quarto-webr#64]
### Bug description

Issue referenced here: https://github.com/coatless/quarto-webr/issues/51

When I am using the webr plugin on this page (https://psy503-f2023.netlify.app/class_notes/06/06-samp_uncert) along with my students they cannot use webr functionality. It is not an issue of packages loading (they said they could load packages but the chunks are greyed out). 

I am not sure what browsers folks are using but I am using Chrome. 

### Your environment

MacOS Monterey 12.4
Chrome browser

**Comment by jgeller112** [comment]
If you need the script it can be found here: https://github.com/jgeller112/PSY503-F2023/blob/main/class_notes/06/06-Samp_Uncert.qmd

**Comment by coatless** [comment]
Can you move the `webr::install()` packages here:

```r
webr::install("tidyverse")
webr::install("gapminder")
webr::install("moderndive")
webr::install("broom")
```

https://github.com/jgeller112/PSY503-F2023/blob/fd0e11f2604e47eef371f2acc23ed66ec3dfa97b/class_notes/06/06-Samp_Uncert.qmd#L48-L51

Into the document header's `package` key above the `filters` statement, e.g. 

```yaml
webr: 
  packages: ['tidyverse', 'gapminder', 'moderndive', 'broom']
filters:
  - webr
```

https://github.com/jgeller112/PSY503-F2023/blob/fd0e11f2604e47eef371f2acc23ed66ec3dfa97b/class_notes/06/06-Samp_Uncert.qmd#L22-L23

This will "lock" code cells until the packages are installed.

**Comment by coatless** [comment]
So, I opened the document and annotate a bit about what's going on:

![Demonstration of webR working on the example document](https://i.imgur.com/tUcOWWA.gif)

<https://i.imgur.com/tUcOWWA.gif>

Note: There is a variable that isn't defined but is being used in the later code cells causing an error 

```r
Error: object 'prop_red' not found
```

```r
prop_red <-as.data.frame(prop_red)
```

https://github.com/jgeller112/PSY503-F2023/blob/fd0e11f2604e47eef371f2acc23ed66ec3dfa97b/class_notes/06/06-Samp_Uncert.qmd#L126

**Comment by jgeller112** [comment]
I leave some code unfinished so we can fill it in during class. The documemt runs for me, but when multiple folks are accessing it at same time causes some errors.

Jason Geller, Ph.D.(he/him/his)
Lecturer
Princeton University
Website: www.drjasongeller.com


On Oct 8, 2023, at 7:57 PM, James J Balamuta ***@***.***> wrote:

﻿

So, I opened the document and annotate a bit about what's going on:

[Demonstration of webR working on the example document]<https://camo.githubusercontent.com/16a36d78336e665648e51dc124cee21ffd021ec305c7c2fbea2cd10807ce9a55/68747470733a2f2f692e696d6775722e636f6d2f7455634f5757412e676966>

https://i.imgur.com/tUcOWWA.gif

Note: There is a variable that isn't defined but is being used in the later code cells causing an error

Error: object 'prop_red' not found

prop_red <-as.data.frame(prop_red)

https://github.com/jgeller112/PSY503-F2023/blob/fd0e11f2604e47eef371f2acc23ed66ec3dfa97b/class_notes/06/06-Samp_Uncert.qmd#L126

**Comment by coatless** [comment]
@jgeller112 I added a global lock in #65 to prevent students from easily moving on to other code cells when the original cell is being created. I'd encourage you to give it a try: 

```sh
quarto add coatless/quarto-webr
```

![Demo showing the global "lock" feature when a single code cell is running](https://github.com/coatless/quarto-webr/assets/833642/0a57e6d1-795b-44b7-afc2-ca76600fee4d)

If there are other issues, please feel free to have the student directly reach out (either here or via e-mail or DM) as I can't re-create a similar scenario on Chrome + macOS.
