### ISSUE TITLE
Package installation not working

### ISSUE THREAD

**Issue by DanielEWeeks** [coatless/quarto-webr#68]
Just updated to the most recent version of quarto-webr using the

`quarto add coatless/quarto-webr`

command and now the loading message on this page 

https://danieleweeks.github.io/HuGen2071/webR_test.html

is more informative than it used to be and it says `Installing 1 of 1 packages: ggplot2`, but when I run the following code block, it dies at the

`library(ggplot2)`

line, stating:

`Error: there is no package called ‘ggplot2’`

However, if I do

`webr::install("ggplot2")`

then the `library(ggplot2)` command works, so a `ggplot2` library is available for this version of webR, but the YAML

```
webr:
  packages: ['ggplot2']
```

is no longer properly installing it.

Thank you.

**Comment by coatless** [comment]
@DanielEWeeks thanks! It should be fixed now.

Could you update the extension again?

```sh
quarto add coatless/quarto-webr
```

**Comment by DanielEWeeks** [comment]
Yes, with this update, webR is now working properly again.  Thank you!
