### ISSUE TITLE
Question about Netlify

### ISSUE THREAD

**Issue by eteitelbaum** [coatless/quarto-webr#8]
Hi @coatless, 

In the readme, you provide instructions to add a few lines of code to the netlify.toml configuration file. My workflow is to push changes to my GitHub repo and then have Netlify to publish the _site file from GitHub. I don't see a netlify.toml file. Should I add it to the root project directory (like where my _quarto.yml file lives)? 

Thanks!

**Comment by eteitelbaum** [comment]
Update, I was able to speed up the loading process significantly by adding a `netlify.toml` file with the code you suggested to the `_site` directory (10s instead of 2m). But it still loads very slowly when I am previewing the site locally. Is there a way to easily change the COOP and COEP HTTP headers so that webR loads faster when I want to render and preview the document on my machine? I mean I see the code that you have there in the README but I don't know what to do with it. Thanks!

**Comment by eteitelbaum** [comment]
Another update. It seems like when I change the COOP and COEP headers in the `netlify.toml` file, my embedded YouTube links don't work. I get an error message saying "youtube refused to connect." Does changing the COOP and COEP settings create security issues that would affect your ability to link to other sites? Thanks.

**Comment by coatless** [comment]
I should mention that this is restricted to Chromium-based browsers so far... e.g. Students would need to use Chrome.

**Comment by eteitelbaum** [comment]
Thanks! I think what I will do for now is move the `webr` chunks to separate practice/exercises page and then wait to mix video and `webr` chunks after the Posit team adds support for credentialless iframes in version 1.4.
