### ISSUE TITLE
`quarto-webr` reading local files

### ISSUE THREAD

**Issue by coatless** [coatless/quarto-webr#9]
@coatless, Is there a solution, then? Can `webr` read local files or is there some other way to load the data? I tried adding a line of code to load the data frame from a local .csv file but it does not work. Thanks.

```r
webr::install(c("dplyr", "readr"))

library(dplyr)
library(readr)

dem_women <- read_csv("data/dem_women.csv")

dem_summary <- dem_women |> 
  group_by(region)  |> 
  summarize(
    polyarchy = mean(polyarchy, na.rm = TRUE),
    gdp_pc = mean(gdp_pc, na.rm = TRUE), 
    flfp = mean(flfp, na.rm = TRUE), 
    women_rep = mean(women_rep, na.rm = TRUE)
  ) |> 
  arrange(desc(polyarchy)) 

dem_summary
```

_Originally posted by @eteitelbaum in https://github.com/coatless/quarto-webr/issues/6#issuecomment-1475416282_

**Comment by coatless** [comment]
@eteitelbaum so, `webr` has a virtual per-session file system. You can explore what's present on the file system using: 

```r
list.files("/", recursive = TRUE, full.names=TRUE)
#   [1] "//dev/null"                                                                  
#   [2] "//dev/random"                                                                
#   [3] "//dev/stderr"                                                                
#   [4] "//dev/stdin"                                                                 
#   [5] "//dev/stdout"                                                                
#   [6] "//dev/tty"                                                                   
#   [7] "//dev/tty1"                                                                  
#   [8] "//dev/urandom"                                                               
#   [9] "//home/web_user/dem_women.csv"                                               
#  [10] "//proc/self/fd"                                                              
# ...
```

webR's default working directory is: 

```r
getwd()
# /home/web_user
```


To get everything activated on the file system, we need to expose some "startup" code inside of the `webr` code cell:

```r
download.file(
  'https://raw.githubusercontent.com/eteitelbaum/dataviz-summer-2023/main/modules/data/dem_women.csv',
  'dem_women.csv'
)

webr::install(c("dplyr", "readr"))

library(dplyr)
library(readr)
dem_women <- read_csv("dem_women.csv")
```

Once this is done, we can then run the example code as-is giving the following output:

<img width="974" alt="webr-file-system-download-csv" src="https://user-images.githubusercontent.com/833642/226214931-73435c76-90f0-41e9-abbb-d1d2b672b73d.png">

Is there a better way to approach it? Yes, but that involves writing some Javascript or further modifications for the extension.

**Comment by eteitelbaum** [comment]
Thanks! I imagine if `webr` had packages that could access various APIs you could just pull the data in that way. Is there a way to request that packages like [rwebstat](https://cran.r-project.org/web/packages/rwebstat/index.html), [fredr](https://cran.r-project.org/web/packages/fredr/vignettes/fredr.html), or [vdemdata](https://github.com/vdeminstitute/vdemdata) be included in `webr` so that you could load them in your `webr` session? 

Also, if I were to do it the way you suggest here I have all of that code at the top of the code chunk, but  basically I wanted to use this as a way to have students play with the code and I fear they might get confused by all of the lines at the top dealing with `webr`. Is there any way to the parts of the code pertaining to the `webr` setup process?

Finally, in terms of the output, is there a way to silence the messages and warnings? Will `webr` respond to Quarto code chunk options like `warning: false`  or `message:fase`?

**Comment by coatless** [comment]
@eteitelbaum I would suggest creating an issue over at the webR's package repo:

<https://github.com/r-wasm/webr-repo/issues>

Before creating one, check each package for dependencies:

```r
library(tidyverse)
deps <- tools::package_dependencies(packages = c('rwebstat', 'fedr', 'vdemdata'),
                                    recursive = TRUE)

tibble(Package=names(deps),
       data=map(deps, as_tibble)) %>% 
  unnest(data)
```

See if the dependencies are present already:
https://github.com/r-wasm/webr-repo/blob/main/repo-packages

Low-dependency packages, packages that do not require extensive C++/Fortran, or offline-focused (no internet required) packages are probably going to be ported in quicker.

----

On the second point, you could try creating a code cell that executes the commands behind the scenes. But, we do not have a specific way to denote an `internal` code cell within the `quarto-webr` extension. I'll add it to the future development board. 

In the interim, you can get away with custom evaluations that could hide the internals, e.g. 

````
```{=html}
<script type="module">
await globalThis.webR.evalRVoid(`
download.file(
  'https://raw.githubusercontent.com/eteitelbaum/dataviz-summer-2023/main/modules/data/dem_women.csv',
  'dem_women.csv'
)

webr::install(c("dplyr", "readr"))

library(dplyr)
library(readr)
dem_women <- read_csv("dem_women.csv")
`)
</script>	
```
````

Or, you could call an external script file via _R_'s `source()` function:

````
```{=html}
<script type="module">
const scriptFiles = [ 
"https://path.com/to-script-file/data-load.R", 
"https://path.com/to-script-file/data-munging.R"];

for (const scriptFileToSource of scriptFiles) {
	console.log(`Sourcing: ${scriptFileToSource}…`)
	await globalThis.webR.evalRVoid(`source("${scriptFileToSource}")`)
}
</script>	
```
````

**Note:** One webR-enabled code cell _must_ appear later in the document to use the above approach.

----

For the third point, we can't separate `message()` from `warning()` as they both are being written to `stderr` at the moment. The best we can do is "respect" the different output streams `stdout` (`cat()` & `print()`) and `stderr` (`message()`, `warning()`, and `stop()`) through a code cell option.

https://github.com/coatless/quarto-webr/blob/2f73a787acb2e5ed36f242d1cbb1f030c5528af8/_extensions/webr/webr-editor.html#L35

Alternatively, you could execute _custom_ cells using `globalThis.webR.evalRVoid()` as given in point 2 to prevent any printing.

**Comment by eteitelbaum** [comment]
Thanks, [it works!](https://dataviz-gwu.rocks/modules/module-1.2.html#group-summarize-and-arrange). And it looks great! 

It does take a long time to load, though (like three minutes?). Would [your tips](https://github.com/coatless/quarto-webr#speed-up-webr) about how to speed up `webr` be relevant here? Or is this slowness just a function of running on a browser as opposed to a server?

**Comment by coatless** [comment]
@eteitelbaum in short, yes. For me, `dplyr` loads at 1776.34 (ms) or 1.77634 (seconds) based on @hrbrmstr's package benchmarking page:

https://rud.is/w/bench/

The full write-up and his conclusion can be found here: 

https://rud.is/b/2023/03/18/webr-wasm-r-package-load-library-benchmarking-rabbit-hole/

**Comment by eteitelbaum** [comment]
OK I did not totally understand what those tips are about but I will do some research. Thanks again.

**Comment by coatless** [comment]
@eteitelbaum the short-gist if you click here:

https://rud.is/w/ggwebr/ggindex.html

This will take 10 seconds.

If you click here:

https://rd.thecoatlessprofessor.com/webR-quarto-demos/webr-quarto-html-demo.html

This will take **at least** 2 minutes.
