### ISSUE TITLE
fa spinner and play button icons don't work when self-contained: true

### ISSUE THREAD

**Issue by alexCardazzi** [coatless/quarto-webr#95]
The spinner and play button of the rendered version of this code fails to load.

````md
---
title: webR in Quarto HTML Documents
format: html
engine: knitr
filters:
  - webr
self-contained: true
---

This is a webr-enabled code cell in a Quarto HTML document.

```{webr-r}
print("hello")
```
````

**Comment by coatless** [comment]
So, the [`self-contained` or `embed-resources`](https://quarto.org/docs/reference/formats/html.html#rendering) is not possible as we can't embed the `webr` client within the document itself. 

You can see some prior discussions at https://github.com/coatless/quarto-webr/issues/62.

**Comment by coatless** [comment]
With #168, you can use `embed-resources` if you are **not** using the `service-worker` communication channel.
