### ISSUE TITLE
Upgrade to webR v0.2.2

### ISSUE THREAD

**Issue by coatless** [coatless/quarto-webr#96]
Steps: 

1. Update `webr-worker.js` and `webr-serviceworker.js` files to `v0.2.2` version.
2. Update included base version in `webr.lua` to `v0.2.2`. 
3. Remove `webr-worker.js` and `webr-serviceworker.js` files from automatically appearing under `channel-type: automatic`
4. Deletion instances from documentation about `webr-worker.js` and `webr-serviceworker.js` files.
5. ???
6. Rejoice that we no longer have to deal with worker files... 

At some point, we really should figure out what's going on with HTML dependencies...

**Comment by ethanwhite** [comment]
Wow, the speed changes with this are dramatic! Thanks!
